name: Nix Package

on:
  workflow_dispatch:

jobs:
  package:
    name: Build default package
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Show initial disk usage
        run: df -h

      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/share/dotnet
          df -h

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show flake outputs
        run: nix flake show --all-systems

      - name: Build package
        run: nix build .#packages.x86_64-linux.default --print-build-logs --show-trace

      - name: Show final disk usage
        if: always()
        run: df -h
